config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'signup', to: "users#new"
  resource :user, only: [:create, :show, :edit, :update]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :posts
  resources :uploads, only: [:create, :destroy]

  resources :banners, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  validates :title, :img, presence: true

  # 画像アップロード
  mount_uploader :img, ImgUploader
end

app/models/post.rb
class Post < ApplicationRecord
  # 乱数生成
  generate_public_uid  generator: PublicUid::Generators::HexStringSecureRandom.new(20)

  # 共通
  validates :title, :body, :urls, presence: true

  # 画像アップロード
  mount_uploader :img, ImgUploader

  def to_param
    public_uid
  end
end

app/models/upload.rb
class Upload < ApplicationRecord
  # 画像アップロード
  mount_uploader :image, ImgUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_save :downcase_email

  # 共通 validates
  validates :email, :password, presence: true

  # name validates
  validates :name, length: { minimum: 1 }

  # email validates
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  # password validates
  has_secure_password
  validates :password, confirmation: true,
                       length: { minimum: 6 },
                       allow_nil: true

  # userimage
  mount_uploader :userimage, ImgUploader

  private
    # メルアドをすべて小文字に変換する
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  # ログインしていない場合
  def login?
    if current_user.nil?
      flash[:danger] = "ログインしてください"
      redirect_to login_path
    end
  end
  # すでにログイン済みの場合
  def logged_in?
    unless current_user.nil?
      redirect_to user_path
    end
  end

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      current_user ||= User.find(session[:user_id])
    end
  end

  def authenticate_user
    if current_user == nil
      redirect_to('/')
    end
  end
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :authenticate_user, except: [:index]

  def index
    @banners = Banner.order(created_at: :desc)
  end

  def new
    @banner = Banner.new
  end
  def create
    @banner = Banner.new(banner_params)
    if @banner.save
      flash[:success] = "保存に成功しました"
      redirect_to :root
    else
      render "new"
    end
  end

    private
      def banner_params
        params.require(:banner).permit(
          :title,
          :img
        )
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.order(created_at: :desc).limit(6)
    @banners = Banner.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]

  def index
    @posts = Post.order(created_at: :desc)
  end

  def show
    @post = Post.find_by(public_uid: params[:id])
  end
  def edit
    @post = Post.find_by(public_uid: params[:id])
  end
  def update
    @post = Post.find_by(public_uid: params[:id])
    if @post.update(post_params)
      flash[:success] = "更新されました"
      redirect_to @post
    else
      render "edit"
    end
  end

  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "保存に成功しました"
      redirect_to @post
    else
      render "new"
    end
  end

  def destroy
    @post = Post.find_by(public_uid: params[:id])
    @post.destroy
    flash[:danger] = "投稿を削除しました"
    redirect_to @post
  end

    private
      def post_params
        params.require(:post).permit(
          :title,
          :img,
          :urls,
          :body,
          :content
          )
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in?, except: :destroy

  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      login(user)
      flash[:success] = "ログインしました"
      redirect_to :root
    else
      flash.now[:danger] = "ログインできませんでした"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:danger] = "ログアウトしました"
    redirect_to :root
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  protect_from_forgery except: :create

  def create
    @upload = Upload.new(upload_params)
    @upload.save

    respond_to do |format|
      format.json{ render :json => { url: @upload.image.url, upload_id: @upload.id } }
    end
  end
  def destroy
    @upload = Upload.find(params[:id])
    @remember_id = @upload.id
    @upload.destroy
    FileUtils.remove_dir("#{Rails.root}/public/uploads/upload/image/#{@remember.id}")
    respond_to do |format|
      format.json{ render :json => { status: :ok} }
    end
  end
    private
      def upload_params
        params.require(:upload).permit(:image)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [:new, :create]
  before_action :login?, only: :show

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "サインアップできました"
      redirect_to user_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(current_user.id)
  end
  def edit
    @user = User.find(current_user.id)
  end
  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:success] = "更新されました"
      redirect_to :user
    else
      render "edit"
    end
  end

    private
      def user_params
        params.require(:user).permit(
          :name,
          :email,
          :userimage,
          :password,
          :password_confirmation)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # タイトル
  def full_title(page_title = '')
    base_title = "Welcome to My Portfolio - 私が担当・制作させて頂いたWebサイトのご紹介"
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end

  def locationUrl
    request.url
  end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/banners/_control_photoswipe.html.erb
<script>
    lightbox.option({
      'resizeDuration': 200,
      'wrapAround': true
    })
</script>

app/views/banners/_form.html.erb
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <div class="custom-file">
    <%= f.file_field :img, class: "custom-file-input", id: "customFile" %>
    <%= f.label :img, name: "img", class: "custom-file-label", for: "customFile" %>
  </div>
</div>
<script>
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>

app/views/banners/index.html.erb
<% provide(:title, "バナー一覧")%>
<div class="container margin-top--md">
<div class="row">
<% @banners.each do |banner| %>
<section class="col-12 col-md-6 col-lg-4 each-section-banners">
<figure class="photoswipe-figure text-center">
  <% if banner.img? %>
    <%= link_to banner.img.url, class: "photoswipe-link d-block", data: { lightbox: "images" } do %>
      <%= image_tag banner.img.url, class: "photoswipe-img" %>
    <% end %>
    <figcaption><%= banner.title %></figcaption>
  <% end %>
</figure>
</section>
<% end %>
</div>
</div>
<%= render "banners/control_photoswipe" %>

app/views/banners/new.html.erb
<% provide(:title, "バナーの新規投稿") %>
<div class="container margin-top--lg">
<div class="row">
<div class="col-12">
<div class="col-12 col-md-6 m-auto">
<h1 class="h3 text-center mb-3"><%= yield(:title) %></h1>
<%= render "shared/error-banner" %>
<%= form_with model: @banner, local: true do |f| %>
<%= render "banners/form", f: f %>
<div class="text-center">
  <%= f.submit "投稿する", class: "btn btn-success" %>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/home/index.html.erb
<div class="top-mainVisual-wrapper">
<div class="container top-mainVisual-container">
<h1 class="text-center top-mainVisual-headline">Welcome to<br>My Portfolio</h1>
<p class="text-center margin-bottom-remove margin-top--sm description">私が担当・制作させて頂いたWebサイトのご紹介</p>
</div>
</div>
<article class="each-wrapper padding-top--lg padding-bottom--lg">
<div class="container">
<div class="row">
<div class="col section-title-container margin-bottom--md">
<h2 class="title-en margin-bottom-remove">Latest</h2>
<p class="title-ja margin-bottom-remove">最新情報</p>
</div>
<% if @posts.present? %>
<div class="col text-right">
  <%= link_to "すべて見る", :posts, class: "btn btn-outline-primary" %>
</div>
<% end %>
</div>
<% if @posts.present? %>
<div class="row">

<% @posts.each do |post| %>
<section class="col-12 col-md-6 col-lg-4 each-section-posts">
  <%= link_to post, class: "d-block each-section-posts-link" do %>
  <div class="each-section-posts-inner">
  <div class="posts-image-container">
    <% if post.img? %>
      <%= image_tag post.img.url, alt: post.title %>
    <% else %>
      <%= image_tag "https://themes.getbootstrap.com/wp-content/uploads/2019/10/screenshot-1-600x450.jpg", class: "img-fluid" %>
    <% end %>
  </div>
  <div class="posts-title-inner">
  <h2 class="posts-title"><%= post.title %></h2>
  <p class="read-more margin-bottom-remove"><i class="fa fa-angle-right" aria-hidden="true"></i>詳しく見る</p>
  </div>
  </div>
  <% end %>
</section>
<% end %>
<div class="col-12 text-center">
  <%= link_to "すべて見る", :posts, class: "btn btn-outline-primary" %>
</div>
<% else %>
<p>まだ投稿がありません。</p>
<% end %>
</div>
</div>
</article>
<article class="each-wrapper padding-top--lg padding-bottom--lg">
<div class="container">
<div class="row">
<div class="col-12 section-title-container margin-bottom--md">
<h2 class="title-en margin-bottom-remove">Banners</h2>
<p class="title-ja margin-bottom-remove">今まで制作させていただいたバナーのご紹介</p>
</div>
</div>
<% if @banners.present? %>
<div class="row">
<% @banners.each do |banner| %>
<section class="col-12 col-md-6 col-lg-4 each-section-banners">
<figure class="photoswipe-figure text-center">
  <% if banner.img? %>
    <%= link_to banner.img.url, class: "photoswipe-link d-block", data: { lightbox: "images" } do %>
      <%= image_tag banner.img.url, class: "photoswipe-img" %>
    <% end %>
    <figcaption><%= banner.title %></figcaption>
  <% end %>
</figure>
</section>
<% end %>
</div>
<%= render "banners/control_photoswipe" %>
<% else %>
<p>まだ投稿がありません</p>
<% end %>

</div>
</div>
</article>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md fixed-top header-nav">
    <div class="container">
        <div class="mr-auto"><%= link_to "My Portfolio", :root, class: "navbar-brand font-weight-bold" %></div>
        <div class="ml-auto">
        <% if current_user %>
        <div class="dropdown">
        <button id="login-user-info" class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if current_user.userimage? %>
        <%= image_tag current_user.userimage.url, id: "img-avatar" %>
        <% else %>
        <%= image_tag ("/uploads/default/default-userimage.svg"), id: "img-avatar" %>
        <% end %>
        </button>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <%= link_to "マイページ", :user, class: "dropdown-item" %>
          <%= link_to "ユーザーを編集する", :edit_user, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "新規投稿する", :new_post, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "バナーの新規投稿をする", :new_banner, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "ログアウトする", :logout, class: "dropdown-item", method: :delete, data: { confirm: "本当にログアウトしますか？" } %>
        </div>
        </div>
        <% elsif Rails.env.development? %>
          <%= link_to "ログイン", :login, class: "btn btn-primary" %>
        <% end %>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/_meta.html.erb
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="format-detection" content="telephone=no">
  <link rel="canonical" href="<%= locationUrl %>">
  <% if current_page?('/') %>
    <meta name="description" content="topページ">
  <% elsif @posts %>
    <meta name="description" content="投稿一覧">
  <% elsif @post %>
    <meta name="description" content="<%= @post.body %>">
  <% end %>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css" integrity="sha512-ZKX+BvQihRJPA8CROKBhDNvoc2aDMOdAlcm7TUQY+35XYtrd3yh95QOOhsPDQY9QnKE0Wqag9y38OIgEvb88cA==" crossorigin="anonymous" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js" integrity="sha512-k2GFCTbp9rQU412BStrcD/rlwv1PYec9SNrkbQlo6RZCf75l6KcC3UwDY8H5n5hl4v77IDtIPwOk9Dqjs/mMBQ==" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
  <meta name="robots" content="noindex" />
    <title><%= full_title(yield(:title)) %></title>
    <%= render "layouts/meta" %>
    <%= render "layouts/rails_default" %>
  </head>

  <% if current_page?(controller: "sessions", action: "new") %>
  <body id="login" class="text-center">
  <% elsif current_page?('/signup') %>
  <body id="signup" class="text-center">
  <% else %>
  <body>
  <%= render "layouts/header" %>
  <% end %>
    <%= yield %>
    <div>
    <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render "shared/error" %>
  </body>
</html>

app/views/posts/_form.html.erb
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <div class="custom-file">
    <%= f.file_field :img, class: "custom-file-input", id: "customFile" %>
    <%= f.label :img, name: "img", class: "custom-file-label", for: "customFile" %>
  </div>
  <p><%= f.check_box :remove_img %> 画像を削除する</p>
</div>
<div class="form-group">
  <%= f.label :urls %>
  <%= f.text_field :urls, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, size: "20x10", class: "form-control" %>
</div>
<div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, 'data-provider': :summernote, class: "form-control", id:"summernote" %>
</div>
<script>
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
$(document).ready(function() {
  $('#summernote').summernote({
    placeholder: '記事本文を入力しましょう',
    tabsize: 3,
    height: 400,
    lang: 'ja-JP', /*日本語対応*/

<<<<<<< HEAD
    onImageUpload: function(files, editor, welEditable) {
        sendFile(files[0], editor,welEditable);
    }
=======
    // onImageUpload: function(files, editor, welEditable) {
    //     sendFile(files[0], editor,welEditable);
    // }
>>>>>>> update-work
    });
  });
</script>

app/views/posts/edit.html.erb
<% provide(:title, "編集する") %>
<div class="container">
<div class="row">
<div class="col-12 padding-top--md padding-bottom--lg">
<h1 class="h3 text-center"><%= yield(:title) %></h1>
<div class="col-12 col-md-6 m-auto">
<%= render "shared/error-post" %>
<%= form_with model: @post, local: true do |f| %>
<%= render "posts/form", f: f %>
<div class="text-center">
  <%= f.submit "更新する", class: "btn btn-success" %>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "投稿一覧") %>
<div class="container margin-top--md">
<div class="row">
<%= render "shared/error" %>
<% if @posts.present? %>
<% @posts.each do |post| %>
<section class="col-12 col-md-6 col-lg-4 each-section-posts">
<%= link_to post, class: "d-block each-section-posts-link" do %>
<div class="each-section-posts-inner">
<div class="posts-image-container">
<% if post.img? %>
<%= image_tag post.img.url, alt: post.title %>
<% else %>
<%= image_tag "https://themes.getbootstrap.com/wp-content/uploads/2019/10/screenshot-1-600x450.jpg", class: "img-fluid" %>
<% end %>
</div>
<div class="posts-title-inner">
<h2 class="posts-title"><%= post.title %></h2>
<p class="read-more margin-bottom-remove"><i class="fa fa-angle-right" aria-hidden="true"></i>詳しく見る</p>
</div>
</div>
<% end %>
</section>
<% end %>
<% else %>
<p>まだ投稿がありません</p>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿する") %>
<div class="container margin-top--lg padding-bottom--lg">
<div class="row">
<div class="col-12">
<div class="col-12 col-md-6 m-auto">
<h1 class="h3 text-center mb-3"><%= yield(:title) %></h1>
<%= render "shared/error-post" %>
<%= form_with model: @post, local: true do |f| %>
<%= render "posts/form", f: f %>
<div class="text-center">
  <%= f.submit "投稿する", class: "btn btn-success" %>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<div class="container margin-top--lg padding-bottom--lg">
<div class="row">
<div class="col-12 col-sm-10 col-md-9 col-lg-8 m-auto">
<div class="row">
<div class="col mb-3">
<%= link_to "投稿一覧", :posts, class: "btn btn-outline-primary" %>
</div>
<% if current_user %>
<div class="col text-right mb-3">
  <button id="btn-authenticate_user-post-info" class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-ellipsis-v" aria-hidden="true"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <%= link_to "編集する", edit_post_path, class: "dropdown-item" %>
    <div class="dropdown-divider"></div>
    <%= link_to "削除する", @post, method: :delete, class: "dropdown-item", data: { confirm: "本当に削除しますか？" } %>
  </div>
</div>
<% end %>
</div>
<h1 class="post-title mb-3"><%= @post.title %></h1>
<time class="small text-monospace d-none" datetime="<%= @post.updated_at %>"><%= @post.updated_at.to_s(:datetime_jp) %></time>
<% if @post.urls? %>
  <%= link_to @post.urls, target: :_blank do %>
    <div class="text-center mb-4 post-mainVisual" <% if @post.img? %> style="background-image: url(<%= @post.img.url %>);">
      <% else %>
    <%= image_tag "https://themes.getbootstrap.com/wp-content/uploads/2019/10/screenshot-1-600x450.jpg", class: "img-fluid" %>
    <% end %>
    </div>
  <% end %>
<% else %>
  <div class="text-center mb-4 post-mainVisual" <% if @post.img? %> style="background-image: url(<%= @post.img.url %>);">
    <% else %>
  <%= image_tag "https://themes.getbootstrap.com/wp-content/uploads/2019/10/screenshot-1-600x450.jpg", class: "img-fluid" %>
    <% end %>
  </div>
<% end %>
<% if @post.urls? %>
<p class="text-right text-url"><%= link_to @post.urls, @post.urls, target: :_blank %></p>
<% else %>

<% end %>
<p class="mb-3"><%= @post.body %></p>
<div id="summernote-editor" class="margin-bottom--lg"><%= @post.content.html_safe %></div>
</div>
</div>

app/views/shared/_error-banner.html.erb
<% if @banner.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">エラーが<%= pluralize(@banner.errors.count, "つあります。") %></h4>
    <hr>
    <ul>
    <% @banner.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error-post.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">エラーが<%= pluralize(@post.errors.count, "つあります。") %></h4>
    <hr>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error-user.html.erb
<% if @user.errors.any? %>
<div id="alert-danger-container" class="col-12 col-md-6 m-auto">
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">エラーが<%= pluralize(@user.errors.count, "つあります。") %></h4>
    <hr>
    <ul id="alert-danger-ul">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_error.html.erb
<% flash.each do |msg_type, msg| %>
<div class="alert-wrapper">
  <div class="alert alert-<%= msg_type %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
<% end %>

app/views/uploads/create.html.erb
<h1>Uploads#create</h1>
<p>Find me in app/views/uploads/create.html.erb</p>

app/views/users/_form.html.erb
  <div class="form-group">
    <%= f.label :name, class: "d-block text-secondary text-left" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "d-block text-secondary text-left" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <div class="custom-file">
      <%= f.file_field :userimage, class: "custom-file-input", id: "customFile" %>
      <%= f.label "ユーザー画像の設定", name: :userimage, class: "custom-file-label", for: "customFile" %>
     </div>
    <script>
    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
    </script>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "d-block text-secondary text-left" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, class: "d-block text-secondary text-left" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集") %>
<div class="container">
<div class="row">
<div class="col-12 margin-top--md">
<h1 class="h3 text-center"><%= yield(:title) %></h1>
<%= render "shared/error-user", obj: @user %>
<div class="col-12 col-md-6 m-auto">
<%= form_with model: @user, local: true do |f| %>
<%= render "users/form", f: f %>
<div class="text-center">
  <%= f.submit "更新する", class: "btn btn-success" %>
</div>
<% end %>
</div>
</div>
</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'サインアップ') %>
<%= render "shared/error-user" %>
<%= form_with model: @user, url: user_path, local: true, class: "form-signin" do |f| %>
<h1 class="h3 font-weight-normal mb-4"><%= yield(:title) %></h1>
  <div class="form-label-group">
    <%= f.email_field :email, class: "form-control", placeholder: "メールアドレスを入力してください" %>
    <%= f.label :email, "メールアドレス" %>
  </div>
  <div class="form-label-group">
    <%= f.password_field :password, class: "form-control", placeholder: "パスワードを入力してください" %>
    <%= f.label :password, "パスワード" %>
  </div>
  <div class="form-label-group">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "確認用としてパスワードをもう一度入力してください" %>
    <%= f.label :password_confirmation %>
  </div>
  <div class="mb-3">
    <%= f.submit 'サインアップ', class: "btn btn-primary" %>
  </div>
  <div>
    <%= link_to "ログインする", login_path %>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "ユーザーネーム：" + current_user.name) %>
<div class="container">
<div class="row">
<div class="col-12 col-md-6 m-auto">
<div class="current_user-container margin-top--md">
<p class="text-center">
<% if current_user.userimage? %>
<%= image_tag current_user.userimage.url, id: "current_user-image", class: "img-fluid" %>
<% else %>
<%= image_tag ("/uploads/default/default-userimage.svg"), id: "current_user-image", class: "img-fluid" %>
<% end %>
</p>
<p class="text-center font-weight-bold current_user-name"><%= current_user.name %></p>
<div class="text-center">
  <%= link_to "プロフィールを編集する", edit_user_path, class: "btn btn-secondary" %>
  <%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-danger", data: { confirm: "本当にログアウトしますか？" } %>
</div>
</div>
</div>
</div>
</div>